apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-wonq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-wonq
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-wonq
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-wonq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-wonq
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-fbdy-tenant/rhtap-demo-app/hacbs-test-project-wonq@sha256:c315e7478c3e5014cf2dbdab291cf91e2fa5ab3e8fdd8293963d4b676bf6b73c
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
